apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bsarathkumar42/testargocd.git
    targetRevision: HEAD
    path: testargocd/argo/springapp
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: springapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
